import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { dirname } from "path";

const html = readFileSync("ui-dist/index.html", "utf-8");
const escaped = JSON.stringify(html);

const output = `// Auto-generated by scripts/embed-ui.js — do not edit
export const UI_HTML = ${escaped};
`;

mkdirSync(dirname("lib/ui-html.ts"), { recursive: true });
writeFileSync("lib/ui-html.ts", output, "utf-8");
console.log("✓ lib/ui-html.ts generated");
